spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xunwu?useUnicode=yes&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  # thymeleaf
  thymeleaf:
    cache: false
  http:
    multipart:
      enabled: true
      location: /Users/gaowenfeng/Documents/IDE/newsell/xunwu-project/xunwu-web/tmp/
      file-size-threshold: 5MB
      max-request-size: 20MB

logging:
  level:
    com:
      gwf:
        xunwu:
          search: debug



